### ISSUE TITLE
Question regarding `to_dask()` method

### ISSUE THREAD

**Issue by andersy005** [ContinuumIO/intake-xarray#26]
I am working on a custom intake plugin for [CMIP5 data sources](https://github.com/NCAR/intake-cmip5), and I am wondering if someone could explain to me why the `to_dask` method of the `DataSourceMixin` source object returns an `xarray.Dataset`? Shouldn’t it be `to_xarray()`? From a user's perspective, would it make sense to have `to_xarray()` instead of `to_dask()`?

**Comment by martindurant** [comment]
I would be OK with `to_xarray` as a more explicit alias for the existing method, but the object returned is daskified (contains dask objects); however, `to_dask` is in the spec base class, so I would prefer to keep that as the main method.

Please feel free to submit a PR to Intake, to include the CMIP5 driver on the list of known plugins. Would you say it is ready for public release?

**Comment by martindurant** [comment]
Thinking about it a moment more, I think the current behaviour is correct: the container type is "xarray", and the `read()` method gives you an in-memory xarray instance, whereas `to_dask()` gives you a dask-oriented version of the same. What do you think?

**Comment by kmpaul** [comment]
Hey, @martindurant!  Thanks for this.

I'm actually wondering if it would make more sense to have `to_xarray()` take an argument that allows you to specify if the data is in-memory or not (i.e., dask-ified).  Maybe something like:

* In-memory implementation:
  `to_xarray(dask=False)`

* Dask-ified implementation:
  `to_xarray(dask=True)`

What do you think about that?  With the default value of `dask=False`.

**Comment by kmpaul** [comment]
Hey, Martin!  Thanks for your feedback.

My main concern is from the "new user" perspective.  I believe that you are correct that this is consistent with design, but I am concerned about whether it is consistent with new user expectations.  And, perhaps more importantly, will the user experience problems if their expectations don't match reality?

For example, regarding the CSV use case, you mention 3 methods that "read" the data and return some data structure: `read()` and `to_dask()` and `to_spark()`.  As you point out, the container type is "dataframe", so it seems obvious to the user that `to_dask()` should return a Dask dataframe and `to_spark()` should return a Spark dataframe.  But is it obvious that `read()` should return a Pandas dataframe?  Maybe a `to_pandas()` method would be more obvious.

Then, what happens if the data is very large.  The naive new user might see the `read()` method and use that, resulting in a memory blow-out.  If the method was named `to_pandas()` there is, at least, _some_ chance that the new user might realize that Pandas is neither lazy nor distributed.

Regarding the xarray use case, I think it is even more confusing for the new user, though.  The container type is "xarray".  That would be analogous to the CSV container type being "pandas", which is not as clear as "dataframe".  So, in the xarray use case, I would argue that the container type should be "dataset" and there should be a `to_xarray()` method that returns an xarray dataset.  The `to_dask()` method is confusing because there is no equivalent "dataset" object in dask.  Instead, xarray uses dask "under the hood" to lazily return an xarray dataset composed of dask arrays (instead of numpy arrays).  So, even with `to_dask()`, you are still returning an xarray dataset.  For that reason, I would argue that the "switch" between numpy arrays and dask arrays should be through an argument (e.g., `dask=True/False`) to the `to_xarray()` method.

Again, the consequences for the naive new user getting this wrong are a memory blow-out.  The `to_dask()` method does suggest to a user that it will be lazy, and shouldn't blow out memory, but the user might ask...what will it return?  Namely, there is no "dataset" equivalent in dask.

I hope you don't take this as argumentative.  I just have strong opinions (😄), and I _**really**_ love intake.  Thanks for the awesome product!

**Comment by andersy005** [comment]
@martindurant, Thank you for the above suggestion. I ended up using it in `intake-cmip` (https://github.com/NCAR/intake-cmip/blob/master/intake_cmip/cmip5.py#L121) for the time being.

**Comment by martindurant** [comment]
OK, that's fine. I will close this issue, in that case. Maybe a similar conversation will need to be had at some point on the intake main repo.
